// src/utils/generateUserPDF.js
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateUserPDF = (user, generatedBy) => {
  if (!user) return;

  const doc = new jsPDF();

  // Header Text
  doc.setFontSize(22);
  doc.setTextColor(44, 62, 80);
  const pageWidth = doc.internal.pageSize.getWidth();
  const titleText = "HeavySync";
  const textWidth = doc.getTextWidth(titleText);
  const textX = (pageWidth - textWidth) / 2;
  doc.text(titleText, textX, 20);

  doc.setFontSize(14);
  doc.setTextColor(79, 70, 229);
  const subTitle = "User Details Report";
  const subTextWidth = doc.getTextWidth(subTitle);
  const subTextX = (pageWidth - subTextWidth) / 2;
  doc.text(subTitle, subTextX, 30);

  // Horizontal line below header
  doc.setDrawColor(79, 70, 229);
  doc.setLineWidth(0.5);
  doc.line(14, 35, 195, 35);

  let currentY = 40;

  // Title
  // doc.setFontSize(18);
  // doc.text("User Details Report", 14, 20);

  // Subtitle
  // doc.setFontSize(12);
  // doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 28);

  // Table Data
  const userData = [
    ["Full Name", `${user.firstName || ""} ${user.lastName || ""}`],
    ["Username", user.username || "N/A"],
    ["Email", user.email || "N/A"],
    ["Mobile", user.mobile || "N/A"],
    ["NIC", user.nic || "N/A"],
    ["Designation", user.designation || "N/A"],
    ["Home Town", user.homeTown || "N/A"],
    ["Role", user.role || "N/A"],
    ["Status", user.status || "N/A"],
    ["Created Date", user.createdDate ? new Date(user.createdDate).toLocaleDateString() : "N/A"],
    ["Employee Number", user.employeeNumber || "N/A"],
  ];

  // Draw Table
  autoTable(doc, {
    startY: currentY + 5,
    head: [["Field", "Value"]],
    body: userData,
    theme: "striped",
    styles: { fontSize: 12 },
    headStyles: { fillColor: [79, 70, 229] },
  });

  // Footer
  doc.setFontSize(10);
  doc.text(`Generated by ${generatedBy || user.username}`, 14, doc.internal.pageSize.height - 10);

  // Save
  doc.save(`${user.username || user.firstName || "user"}_Details.pdf`);
};